<?php

if (count($this->data)) {

?>
<div class="pane pane_portfolio">
	<h2>Последние посты блога</h2>
	<table>
<?php



	foreach ($this->data as $n => $el) {


?>
	<tr<?php echo $n == count($this->data) - 1 ? ' class="last"' : '' ?>>
		<td class="f"><h4><a href="<?php echo $el->url_valid ?>" title="Читать подробнее"><?php echo $el->topic_title ?></a></h4></td>
		<td class="new"><span<?php echo $el->is_new ? ' title="Новинка"' : '' ?> class="i i-star<?php echo $el->is_new ? '' : 'off' ?>"></span></td>
		<td class="studia"><a href="<?php echo $el->url_user_valid ?>" title="Смотреть информацию о пользователе"><?php echo $el->user_stitle ?></a></td>
		<td class="date l" title="Дата публикации"><?php echo rtrim($el->topic_date_add_valid, '0123456789 ') ?></td>
	</tr>
<?php

	}

?>
	</table>
</div>
<?php

}