<?php

$this->layout()->disableLayout(true);

$model = new Default_Model_Portfolio();
$model_s = new Default_Model_Studia();
$model_p = new Default_Model_Parser();

$list = $model_s->fetchNotPortfolioParsed();
$model->update(array('active' => 0), '`parsed` = 1 AND UNIX_TIMESTAMP(`parsed`) + 86400 * 5 < UNIX_TIMESTAMP(NOW())');
if (count($list)) {
	$new = $news = array();
	set_time_limit(3600);
	foreach ($list as $el) {
		$items_new = $model_p->parseJson($el->src_portfolio ? $el->src_portfolio : $el->url.'/vololo.json');
		if ($items_new === false) $items_new = $model_p->{'parsePortfolio'.ucfirst($el->stitle)}();
		$model_s->update(array('parsed_portfolio' => date('Y-m-d H:i:s')), array('`id` = ?' => $el->id));
		if ($items_new && count($items_new)) {
			foreach ($items_new as $item) {
				$item['parentid'] = $el->id;
				$item['parsed'] = date('Y-m-d H:i:s');
				$item['active'] = 1;
				$exist = $model->fetchByOid($el->id, $item['oid']);
				if ($exist) $model->update($item, array('`id` = ?' => $exist->id));
				else {
					$ok = $model->insert($item);
					if ($ok) {
						$new[] = $ok;
						if (!in_array($el->id, $news)) $news[] = $el->id;
					}
				}
			}
		}
	}
	if ($new && $news) {
		$this->partial('twitter/send.phtml', array(
			'items' => array(
				'portfolio' => $new
			)
		));
		$this->partial('mail/send.phtml', array(
			'items' => array(
				'portfolio' => $new
			),
			'studios' => $news
		));
	}
}